name: Auto merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: |
      github.actor == 'Gonzalopaz41' ||
      github.actor == 'illeiva2'     ||
      github.actor == 'RominaGG'     ||
      github.actor == 'ignatole'     ||
      github.actor == 'Lauce'
    runs-on: ubuntu-latest
    steps:
      - name: Esperar que GitHub calcule mergeability
        run: sleep 10

      - name: Obtener estado del PR
        id: prdata
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            core.setOutput('mergeable', pr.mergeable);
            core.setOutput('number', pr.number);
      
      - name: Hacer merge si es posible
        if: steps.prdata.outputs.mergeable == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt('${{ steps.prdata.outputs.number }}'),
              merge_method: 'squash'
            });

